// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🔥 Web config (from your Firebase console)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBzMdsUVR1194W2LYmmO3us0KrHsNrO4RY",
    authDomain: "my-habit-tracker-b1cdc.firebaseapp.com",
    projectId: "my-habit-tracker-b1cdc",
    storageBucket: "my-habit-tracker-b1cdc.firebasestorage.app",
    messagingSenderId: "955570163418",
    appId: "1:955570163418:web:a0dd28d0d67bcd16839fe3",
  );

  /// ✅ If you created Android app in Firebase console,
  /// replace with the Android config values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBzMdsUVR1194W2LYmmO3us0KrHsNrO4RY",
    appId: "1:955570163418:android:xxxxxxxxxxxxxxxx", // 👈 from Firebase console
    messagingSenderId: "955570163418",
    projectId: "my-habit-tracker-b1cdc",
    storageBucket: "my-habit-tracker-b1cdc.firebasestorage.app",
  );

  /// ✅ If you created iOS app in Firebase console,
  /// replace with the iOS config values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBzMdsUVR1194W2LYmmO3us0KrHsNrO4RY",
    appId: "1:955570163418:ios:b99171aa0b03b0ac839fe3", // 👈 from Firebase console
    messagingSenderId: "955570163418",
    projectId: "my-habit-tracker-b1cdc",
    storageBucket: "my-habit-tracker-b1cdc.firebasestorage.app",
    iosBundleId: "com.example.habithero", // update to your real bundle ID
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = web;
}
