// utils/local_quotes.dart
final Map<String, List<String>> localQuotes = {
  "Motivation": [
    "Believe you can and you're halfway there.",
    "Success starts with self-belief.",
    "Action is the foundational key to all success.",
    "Your only limit is your mind.",
    "Start where you are. Use what you have. Do what you can.",
    "Small steps every day lead to big changes.",
    "Energy and persistence conquer all things.",
    "Focus on progress, not perfection.",
    "Push harder today if you want a better tomorrow.",
    "Dream big, start small, act now.",
    "Your future is created by what you do today, not tomorrow.",
  ],
  "Discipline": [
    "Discipline is doing what needs to be done, even when you don't want to.",
    "Self-control is strength. Right thought is mastery.",
    "Consistency beats motivation every time.",
    "Your habits define your success.",
    "Discipline creates freedom, laziness creates regret.",
    "Master yourself, master your life.",
    "Daily practice leads to lifelong excellence.",
    "The road to success is paved with discipline.",
    "Small disciplined actions lead to big achievements.",
    "Discipline is the silent architect of greatness.",
  ],
  "Success": [
    "Success is built one small win at a time.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Success is not for the chosen few, but for the persistent few.",
    "The key to success is to start before you are ready.",
    "Every success story begins with a single step.",
    "Success comes from effort, perseverance, and learning.",
    "Your attitude determines your altitude.",
    "Don’t just wait for opportunities—create them.",
    "Greatness is achieved by ordinary people who refuse to quit.",
    "Success is the sum of small efforts repeated consistently.",
  ],
  "Habits": [
    "Habits shape your destiny.",
    "What you do today can improve all your tomorrows.",
    "Consistency is more important than perfection.",
    "Good habits are the foundation of a great life.",
    "Your habits reveal your priorities.",
    "Excellence is built on daily habits.",
    "The key to change is forming better habits.",
    "Habits are the invisible architecture of your life.",
    "Small actions repeated lead to massive results.",
    "Invest in habits that build the life you want.",
  ],
  "Growth": [
    "Growth happens outside your comfort zone.",
    "Every challenge is an opportunity to grow.",
    "The mind grows by stretching beyond the familiar.",
    "Your potential expands when you push your limits.",
    "Mistakes are stepping stones to growth.",
    "Growth requires patience and perseverance.",
    "Learning is the path to personal evolution.",
    "Change is growth in action.",
    "Adaptability is the key to continuous improvement.",
    "True growth begins when you embrace discomfort.",
  ],
  "Wisdom": [
    "Wisdom comes from experience and reflection.",
    "Listen more than you speak.",
    "The wise understand that learning never ends.",
    "Patience is the companion of insight.",
    "Seek knowledge, but value understanding.",
    "Wise people act with clarity and purpose.",
    "Learning from mistakes is the essence of wisdom.",
    "Understanding others is the foundation of wisdom.",
    "Think before you act; wisdom grows in reflection.",
    "Wisdom is knowing the right path and walking it.",
  ],
  "Mindfulness": [
    "Be present in every moment.",
    "Awareness brings peace.",
    "Focus on your breath, not your thoughts.",
    "Mindfulness is the art of being here now.",
    "Notice the small things—they hold great meaning.",
    "Calm mind, peaceful life.",
    "Observe without judgment.",
    "Mindfulness is the gateway to happiness.",
    "Slow down and savor the moment.",
    "Awareness of now is the key to clarity and joy.",
  ],
};
